version: "3.9"

services:
  form-service-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: puppy
      POSTGRES_PASSWORD: Abat228
      POSTGRES_DB: form-service-db
    ports:
      - 5433:5432

  form-service-adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: dracula
    ports:
      - 3333:8080